### ISSUE TITLE
Bug: 表示の崩れ

### ISSUE THREAD

**Issue by yatakabs** [rakkyo150/PredictStarNumberExtension#1]
## Summary
非ランク曲の場合 Party Error / Parity Warning の表示があるため `i` に要素を追加すると表示が崩れます。
代わりに、☆表示用の `span` を `div` の手前に置くことでこれを回避できます。

### 大幅表示
![image](https://user-images.githubusercontent.com/87169907/160995927-81886272-20b9-4522-97bd-f30d8d5a6e95.png)

### 中幅表示
![image](https://user-images.githubusercontent.com/87169907/160995901-5f6d4c02-dfa8-4de4-a0ef-e624bb8d0d27.png)

### 小幅表示
![image](https://user-images.githubusercontent.com/87169907/160995945-4960bb2b-19c5-4f94-91f3-4311f59e00b3.png)

**Comment by rakkyo150** [comment]
なるほど。
あまり何も考えず`span`をランク譜面と同じ位置にいれていましたが、確かに`div`の手前に置けば表示崩れ解決しますね。
勉強になりました。
ありがとうございます。
